# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10ed01979479738390a88e4481ed8d07070fe61ba390f13c874e862ad14bfd6eef60edc461ddeb55a7c0abd4f0e7ab374b2a6461c4f5d8f0248ecd7ea1ef172f

test:
  secret_key_base: 0815955ac51e59ab80ff10cc5ad52939b341fd1ff603b8c1fdfdcc2a8e4e7ece8c276939a3280cbd67ddd117657c8300ff06163887c30b52e465e77e59ef3c06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
